**Task 4.1: Pandas Basics**
Create a Pandas Series of 10 random integers between 1 and 100

In [31]:
import numpy as np
import pandas as pd

Print the following:
The Series

In [32]:
data=pd.Series(np.random.randint(1,101,size=10))
data

0    93
1    18
2    53
3     3
4    87
5    73
6    50
7    74
8    63
9    63
dtype: int32

The first 5 elements

In [33]:
data.head()

0    93
1    18
2    53
3     3
4    87
dtype: int32

The last 5 elements

In [34]:
data.tail()

5    73
6    50
7    74
8    63
9    63
dtype: int32

The maximum and minimum value

In [35]:
print("maximum value is: ",data.max())
print("minimum value is: ",data.min())

maximum value is:  93
minimum value is:  3

The mean of the Series

In [36]:
data.mean()

np.float64(57.7)

Convert the Series into a Python list and print it.

In [37]:
data.tolist()

[93, 18, 53, 3, 87, 73, 50, 74, 63, 63]

**Task 4.2:Pandas DataFrame Operations**
Create a Pandas DataFrame with the following data:

In [38]:
pf={"Name":["Adi","Bobby","Candy","Dior","Ena"],
"Age":[20,21,19,22,20],
"Marks":[85,90,75,95,88]}
df=pd.DataFrame(pf)
df

    Name  Age  Marks
0    Adi   20     85
1  Bobby   21     90
2  Candy   19     75
3   Dior   22     95
4    Ena   20     88

Print the first 3 rows of the DataFrame

In [39]:
df.head(3)

    Name  Age  Marks
0    Adi   20     85
1  Bobby   21     90
2  Candy   19     75

Print only the Name column

In [40]:
df["Name"]

0      Adi
1    Bobby
2    Candy
3     Dior
4      Ena
Name: Name, dtype: object

Print the row where Marks is greater than 85

In [41]:
df[df["Marks"]>85]

    Name  Age  Marks
1  Bobby   21     90
3   Dior   22     95
4    Ena   20     88

Add a new column Grade with values of your choice (like A, B, C, etc.)

In [42]:
df["Grade"]=["B+","A","C","A+","A+"]
df

    Name  Age  Marks Grade
0    Adi   20     85    B+
1  Bobby   21     90     A
2  Candy   19     75     C
3   Dior   22     95    A+
4    Ena   20     88    A+

Drop the Age column and display the modified DataFrame

In [43]:
df2=df.drop(columns=["Age"])
df2

    Name  Marks Grade
0    Adi     85    B+
1  Bobby     90     A
2  Candy     75     C
3   Dior     95    A+
4    Ena     88    A+

Task 4.3: Pandas Data Analysis
Create a Pandas DataFrame with 10 students and the following columns: Name, Maths, Science, English. (Fill with random marks between 50 and 100).

In [44]:
dataf=pd.DataFrame({"Name":["ankit","aman","harkesh","pushkal","charchil","vikas","krish","harsh vardhan","ansh negi","rakshit"],
"Maths":np.random.randint(50,101,10),
"Science":np.random.randint(50,101,10),
"English":np.random.randint(50,101,10)})

Perform the following operations:
Print the average marks of each subject

In [45]:
dataf[["Maths","Science","English"]].mean()

Maths      78.0
Science    83.6
English    80.0
dtype: float64

Add a new column Total which is the sum of marks across the three subjects

In [46]:
dataf["Total"]=dataf[["Maths","Science","English"]].sum(axis=1)
dataf

            Name  Maths  Science  English  Total
0          ankit     82       88      100    270
1           aman     74       69       94    237
2        harkesh     81       98       96    275
3        pushkal     99       55       87    241
4       charchil     59       85       68    212
5          vikas     74       89       80    243
6          krish     86       90       80    256
7  harsh vardhan     95       93       67    255
8      ansh negi     50       99       72    221
9        rakshit     80       70       56    206

⦁	Print the student with the highest total marks

In [47]:
dataf.loc[dataf["Total"].idxmax()]

Name       harkesh
Maths           81
Science         98
English         96
Total          275
Name: 2, dtype: object

⦁Add another column Result where the value is 'Pass' if the student has total marks ≥ 150, otherwise 'Fail

In [48]:
dataf["RESULT"]=np.where(dataf["Total"]>=150,"PASS","FAIL")

In [49]:
dataf

            Name  Maths  Science  English  Total RESULT
0          ankit     82       88      100    270   PASS
1           aman     74       69       94    237   PASS
2        harkesh     81       98       96    275   PASS
3        pushkal     99       55       87    241   PASS
4       charchil     59       85       68    212   PASS
5          vikas     74       89       80    243   PASS
6          krish     86       90       80    256   PASS
7  harsh vardhan     95       93       67    255   PASS
8      ansh negi     50       99       72    221   PASS
9        rakshit     80       70       56    206   PASS

⦁	Sort the DataFrame by Total in descending order

In [50]:
dataf=dataf.sort_values("Total",ascending=False)
dataf

            Name  Maths  Science  English  Total RESULT
2        harkesh     81       98       96    275   PASS
0          ankit     82       88      100    270   PASS
6          krish     86       90       80    256   PASS
7  harsh vardhan     95       93       67    255   PASS
5          vikas     74       89       80    243   PASS
3        pushkal     99       55       87    241   PASS
1           aman     74       69       94    237   PASS
8      ansh negi     50       99       72    221   PASS
4       charchil     59       85       68    212   PASS
9        rakshit     80       70       56    206   PASS