**DATA CLEANING**

In [34]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv('zomato.csv',encoding='latin-1')

In [36]:
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [37]:
print(df.shape)
print(df.head())
print(df.tail())
print(df.info())
print(df.columns)

(7105, 12)
   Unnamed: 0.1  Unnamed: 0     restaurant name restaurant type  \
0             0           0        #FeelTheROLL     Quick Bites
1             1           1          #L-81 Cafe     Quick Bites
2             2           2             #refuel            Cafe
3             3           3  '@ Biryani Central   Casual Dining
4             4           4          '@ The Bbq   Casual Dining

   rate (out of 5)  num of ratings  avg cost (two people) online_order  \
0              3.4               7                  200.0           No
1              3.9              48                  400.0          Yes
2              3.7              37                  400.0          Yes
3              2.7             135                  550.0          Yes
4              2.8              40                  700.0          Yes

  table booking                                      cuisines type  \
0            No                                          Fast Food
1            No                               Fast Food, Beverages
2            No                                    Cafe, Beverages
3            No                          Biryani, Mughlai, Chinese
4            No  BBQ, Continental, North Indian, Chinese, Bever...

                             area      local address
0                       Bellandur          Bellandur
1  Byresandra,Tavarekere,Madiwala                HSR
2               Bannerghatta Road  Bannerghatta Road
3                    Marathahalli       Marathahalli
4                       Bellandur          Bellandur
      Unnamed: 0.1  Unnamed: 0         restaurant name     restaurant type  \
7100          7100        7100                  Zoey's                Cafe
7101          7101        7101  ZOROY Luxury Chocolate      Dessert Parlor
7102          7102        7102       Zu's Doner Kebaps  Takeaway, Delivery
7103          7103        7103                   Zyara       Casual Dining
7104          7104        7104                  Zyksha          Food Truck

      rate (out of 5)  num of ratings  avg cost (two people) online_order  \
7100              4.3             894                  600.0          Yes
7101              4.0              68                  250.0          Yes
7102              3.7              33                  350.0           No
7103              3.8             191                  650.0          Yes
7104              3.4               9                  200.0           No

     table booking                         cuisines type               area  \
7100            No    Cafe, Italian, Continental, Burger          Bellandur
7101            No                              Desserts       Brigade Road
7102            No  Turkish, Fast Food, Biryani, Chinese       Malleshwaram
7103            No        North Indian, Mughlai, Chinese       Kammanahalli
7104            No                             Fast Food  Bannerghatta Road

        local address
7100    Sarjapur Road
7101    Church Street
7102         RT Nagar
7103       HBR Layout
7104  South Bangalore
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB
None
Index(['Unnamed: 0.1', 'Unnamed: 0', 'restaurant name', 'restaurant type',
       'rate (out of 5)', 'num of ratings', 'avg cost (two people)',
       'online_order', 'table booking', 'cuisines type', 'area',
       'local address'],
      dtype='object')

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.dtypes

Unnamed: 0.1               int64
Unnamed: 0                 int64
restaurant name           object
restaurant type           object
rate (out of 5)          float64
num of ratings             int64
avg cost (two people)    float64
online_order              object
table booking             object
cuisines type             object
area                      object
local address             object
dtype: object

In [40]:
df["online_order"].unique()

array(['No', 'Yes'], dtype=object)

In [41]:
df.drop(columns=['Unnamed: 0.1','Unnamed: 0'],inplace=True)
df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [42]:
df["rate (out of 5)"].fillna(df["rate (out of 5)"].mean(),inplace=True)
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20932\3777873587.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["rate (out of 5)"].fillna(df["rate (out of 5)"].mean(),inplace=True)

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [43]:
df["avg cost (two people)"].fillna(df["avg cost (two people)"].median(),inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20932\232483792.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["avg cost (two people)"].fillna(df["avg cost (two people)"].median(),inplace=True)

In [44]:
df.drop_duplicates(inplace=True)

In [45]:
df.isnull().sum()

restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

In [46]:
for i in ["restaurant name","restaurant type","cuisines type","area","local address"]:
    df[i]=df[i].str.strip()

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df.to_csv("zomato_cleaned.csv",index=False)

In [52]:
df_cleaned=pd.read_csv('zomato_cleaned.csv')
pd.set_option('display.max_columns',None)
pd.set_option('display.width',None)
df_cleaned

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore